services:
  ecs-postgres:
    image: 'postgres:latest'
    container_name: dhsf-local-db
    ports:
      - "5433:5432"
    volumes:
      - ../../db/dhsf-local-db:/var/lib/postgresql:rw
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d dhsf -U dhsf" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: dhsf
      POSTGRES_USER: dhsf
      POSTGRES_PASSWORD: dhsf